import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Phase 2 foundation: users, vendors, stores, categories, products,
 * product_images, product_variants, inventory, addresses.
 *
 * Hand-written rather than autogenerated — see the Phase 2 report for why
 * (no reachable Postgres instance in the authoring environment to diff
 * against). Every column/constraint here matches the entities in
 * src/entities exactly; treat this file, not the decorators, as the
 * authoritative DDL if the two are ever compared.
 */
export class InitialSchema1755280000000 implements MigrationInterface {
  name = 'InitialSchema1755280000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

    await queryRunner.query(
      `CREATE TYPE "users_role_enum" AS ENUM ('customer', 'vendor', 'admin')`,
    );
    await queryRunner.query(
      `CREATE TYPE "vendors_status_enum" AS ENUM ('pending', 'approved', 'rejected', 'suspended')`,
    );
    await queryRunner.query(
      `CREATE TYPE "products_status_enum" AS ENUM ('draft', 'active', 'inactive', 'archived')`,
    );

    // ---------------------------------------------------------------- users
    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "email" varchar(255) NOT NULL,
        "password_hash" varchar(255) NOT NULL,
        "first_name" varchar(100) NOT NULL,
        "last_name" varchar(100) NOT NULL,
        "photo_url" varchar(500),
        "role" "users_role_enum" NOT NULL DEFAULT 'customer',
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "PK_users" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_users_email" UNIQUE ("email")
      )
    `);

    // -------------------------------------------------------------- vendors
    await queryRunner.query(`
      CREATE TABLE "vendors" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "user_id" uuid NOT NULL,
        "status" "vendors_status_enum" NOT NULL DEFAULT 'pending',
        "business_name" varchar(255) NOT NULL,
        "tax_id" varchar(100),
        "stripe_account_id" varchar(255),
        "payout_details" jsonb,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_vendors" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_vendors_user_id" UNIQUE ("user_id"),
        CONSTRAINT "UQ_vendors_stripe_account_id" UNIQUE ("stripe_account_id"),
        CONSTRAINT "FK_vendors_user" FOREIGN KEY ("user_id")
          REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_vendors_status" ON "vendors" ("status")`,
    );

    // ----------------------------------------------------------- categories
    await queryRunner.query(`
      CREATE TABLE "categories" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "name" varchar(255) NOT NULL,
        "slug" varchar(255) NOT NULL,
        "image_url" varchar(500),
        "background_color" varchar(50),
        "parent_id" uuid,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_categories" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_categories_slug" UNIQUE ("slug"),
        CONSTRAINT "UQ_category_parent_name" UNIQUE ("parent_id", "name"),
        CONSTRAINT "FK_categories_parent" FOREIGN KEY ("parent_id")
          REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_categories_parent_id" ON "categories" ("parent_id")`,
    );
    // Composite UNIQUE (parent_id, name) above can't stop duplicate root
    // names, since Postgres treats every NULL parent_id as distinct from
    // every other NULL. This partial index closes that gap explicitly.
    await queryRunner.query(`
      CREATE UNIQUE INDEX "UQ_categories_root_name" ON "categories" ("name")
      WHERE "parent_id" IS NULL
    `);

    // --------------------------------------------------------------- stores
    await queryRunner.query(`
      CREATE TABLE "stores" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "vendor_id" uuid NOT NULL,
        "name" varchar(255) NOT NULL,
        "slug" varchar(255) NOT NULL,
        "description" text,
        "logo_url" varchar(500),
        "is_active" boolean NOT NULL DEFAULT true,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "PK_stores" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_stores_slug" UNIQUE ("slug"),
        CONSTRAINT "FK_stores_vendor" FOREIGN KEY ("vendor_id")
          REFERENCES "vendors"("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_stores_vendor_id" ON "stores" ("vendor_id")`,
    );

    // ------------------------------------------------------------- products
    await queryRunner.query(`
      CREATE TABLE "products" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "store_id" uuid NOT NULL,
        "category_id" uuid NOT NULL,
        "name" varchar(255) NOT NULL,
        "slug" varchar(255) NOT NULL,
        "description" text,
        "status" "products_status_enum" NOT NULL DEFAULT 'draft',
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "PK_products" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_product_store_slug" UNIQUE ("store_id", "slug"),
        CONSTRAINT "FK_products_store" FOREIGN KEY ("store_id")
          REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "FK_products_category" FOREIGN KEY ("category_id")
          REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_products_store_id" ON "products" ("store_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_products_category_id" ON "products" ("category_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_products_status" ON "products" ("status")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_products_store_category" ON "products" ("store_id", "category_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_products_active" ON "products" ("id") WHERE "deleted_at" IS NULL`,
    );

    // -------------------------------------------------------- product_images
    await queryRunner.query(`
      CREATE TABLE "product_images" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "product_id" uuid NOT NULL,
        "url" varchar(500) NOT NULL,
        "position" smallint NOT NULL DEFAULT 0,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_product_images" PRIMARY KEY ("id"),
        CONSTRAINT "FK_product_images_product" FOREIGN KEY ("product_id")
          REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_product_images_product_id" ON "product_images" ("product_id")`,
    );

    // ------------------------------------------------------ product_variants
    await queryRunner.query(`
      CREATE TABLE "product_variants" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "product_id" uuid NOT NULL,
        "sku" varchar(100) NOT NULL,
        "attributes" jsonb,
        "price" numeric(12,2) NOT NULL,
        "discount_price" numeric(12,2),
        "currency" varchar(3) NOT NULL DEFAULT 'USD',
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "PK_product_variants" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_product_variants_sku" UNIQUE ("sku"),
        CONSTRAINT "CHK_variant_price_non_negative" CHECK ("price" >= 0),
        CONSTRAINT "CHK_variant_discount_price_valid"
          CHECK ("discount_price" IS NULL OR "discount_price" <= "price"),
        CONSTRAINT "FK_product_variants_product" FOREIGN KEY ("product_id")
          REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_product_variants_product_id" ON "product_variants" ("product_id")`,
    );

    // -------------------------------------------------------------- inventory
    await queryRunner.query(`
      CREATE TABLE "inventory" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "variant_id" uuid NOT NULL,
        "stock_quantity" integer NOT NULL DEFAULT 0,
        "reserved_quantity" integer NOT NULL DEFAULT 0,
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_inventory" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_inventory_variant_id" UNIQUE ("variant_id"),
        CONSTRAINT "CHK_inventory_stock_non_negative" CHECK ("stock_quantity" >= 0),
        CONSTRAINT "CHK_inventory_reserved_non_negative" CHECK ("reserved_quantity" >= 0),
        CONSTRAINT "CHK_inventory_reserved_lte_stock" CHECK ("reserved_quantity" <= "stock_quantity"),
        CONSTRAINT "FK_inventory_variant" FOREIGN KEY ("variant_id")
          REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);

    // -------------------------------------------------------------- addresses
    await queryRunner.query(`
      CREATE TABLE "addresses" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "user_id" uuid NOT NULL,
        "street_address" varchar(255) NOT NULL,
        "city" varchar(100) NOT NULL,
        "area" varchar(100) NOT NULL,
        "country" varchar(100) NOT NULL,
        "postal_code" varchar(20) NOT NULL,
        "is_default" boolean NOT NULL DEFAULT false,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "PK_addresses" PRIMARY KEY ("id"),
        CONSTRAINT "FK_addresses_user" FOREIGN KEY ("user_id")
          REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_addresses_user_id" ON "addresses" ("user_id")`,
    );
    // Partial unique index: at most one default, non-deleted address per user.
    await queryRunner.query(`
      CREATE UNIQUE INDEX "UQ_addresses_default_per_user" ON "addresses" ("user_id")
      WHERE "is_default" = true AND "deleted_at" IS NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "addresses"`);
    await queryRunner.query(`DROP TABLE "inventory"`);
    await queryRunner.query(`DROP TABLE "product_variants"`);
    await queryRunner.query(`DROP TABLE "product_images"`);
    await queryRunner.query(`DROP TABLE "products"`);
    await queryRunner.query(`DROP TABLE "stores"`);
    await queryRunner.query(`DROP TABLE "categories"`);
    await queryRunner.query(`DROP TABLE "vendors"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TYPE "products_status_enum"`);
    await queryRunner.query(`DROP TYPE "vendors_status_enum"`);
    await queryRunner.query(`DROP TYPE "users_role_enum"`);
  }
}
